In [16]:
import numpy as np

In [17]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

input_data = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1]
])

learning_rate = 0.1
epochs =  10000

In [19]:
weights_hidden = np.random.random((8, 3))
bias_hidden = np.random.random((1, 3))

weights_output = np.random.random((3, 8))
bias_output = np.random.random((1, 8))

for epoch in range(epochs):
    for i, data in enumerate(input_data):
        input = data.reshape((1, -1))
        hidden_layer_input = (input @ weights_hidden) + bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)

        output_layer_input = (hidden_layer_output @ weights_output) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        error = output_layer_output - input

        delta_output = output_layer_output * (1 - output_layer_output) * error
        delta_hidden = hidden_layer_output * (1 - hidden_layer_output) * (delta_output @ weights_output.T)

        weights_output -= (learning_rate) * np.dot(hidden_layer_output.T, delta_output)
        bias_output -= (learning_rate) * np.sum(delta_output, axis=0, keepdims=True)

        weights_hidden -= (learning_rate) * np.dot(input.T, delta_hidden)
        bias_hidden -= (learning_rate) * np.sum(delta_hidden, axis=0, keepdims=True)

print("Final predictions")
input = input_data
hidden_state = sigmoid(input @ weights_hidden  + bias_hidden)
output = sigmoid(hidden_state @ weights_output  + bias_output)
print(np.round(output, 2))

print("Hidden states")
print(np.round(hidden_state,3))


Final predictions
[[0.91 0.   0.02 0.   0.   0.06 0.   0.05]
 [0.   0.92 0.   0.02 0.   0.07 0.   0.03]
 [0.07 0.   0.93 0.   0.07 0.   0.05 0.  ]
 [0.   0.08 0.   0.92 0.07 0.   0.07 0.  ]
 [0.   0.   0.07 0.09 0.86 0.   0.   0.07]
 [0.04 0.03 0.   0.   0.   0.9  0.03 0.  ]
 [0.   0.   0.01 0.02 0.   0.06 0.92 0.  ]
 [0.06 0.05 0.   0.   0.09 0.   0.   0.91]]
Hidden states
[[0.99  0.026 0.905]
 [0.013 0.969 0.875]
 [0.851 0.01  0.022]
 [0.012 0.764 0.021]
 [0.031 0.014 0.207]
 [0.976 0.988 0.982]
 [0.887 0.958 0.009]
 [0.156 0.051 0.987]]


In [11]:
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights_hidden = np.random.random((8, 3))
        self.bias_hidden = np.random.random((1, 3))

        self.weights_output = np.random.random((3, 8))
        self.bias_output = np.random.random((1, 8))

    def feedforward(self, X):
        X = X.reshape((1, -1))
        self.hidden_layer_input = np.dot(X, self.weights_hidden) + self.bias_hidden
        self.hidden_layer_output = sigmoid(self.hidden_layer_input)

        self.output_layer_input = np.dot(self.hidden_layer_output, self.weights_output) + self.bias_output
        self.output_layer_output = sigmoid(self.output_layer_input)

    def backprop(self, X, y, learning_rate):
        output_error = y - self.output_layer_output
        delta_output = self.output_layer_output * (1 - self.output_layer_output) * output_error

        delta_hidden = self.hidden_layer_output * (1 - self.hidden_layer_output) * np.dot(delta_output, self.weights_output.T)

        self.weights_output -= (learning_rate) * np.dot(self.hidden_layer_output.T, delta_output)
        self.bias_output -= (learning_rate) * np.sum(delta_output, axis=0, keepdims=True)

        self.weights_hidden -= (learning_rate) * np.dot(X.T, delta_hidden)
        self.bias_hidden -= (learning_rate) * np.sum(delta_hidden, axis=0, keepdims=True)


    def train(self, X, y, epochs, learning_rate):
        for _ in range(epochs):
            self.feedforward(X)
            self.backprop(X, y, learning_rate)

    def predict(self, X):
        self.feedforward(X)
        return self.output_layer_output


In [12]:
if __name__ == "__main__":
    input_data = np.array([[1, 0, 0, 0, 0, 0, 0],
                           [0, 1, 0, 0, 0, 0, 0],
                           [0, 0, 1, 0, 0, 0, 0],
                           [0, 0, 0, 1, 0, 0, 0],
                           [0, 0, 0, 0, 1, 0, 0],
                           [0, 0, 0, 0, 0, 1, 0],
                           [0, 0, 0, 0, 0, 0, 1]])

    input_size = input_data.shape[1]
    hidden_size = 4
    learning_rate = 5
    epochs = 500
    nn = NeuralNetwork(input_size, hidden_size, input_size)
    nn.train(input_data, input_data, epochs, learning_rate)

    for i in range(len(input_data)):
        prediction = nn.predict(input_data[i])
        print(f"Input: {input_data[i]}, Predicted Output: {prediction}")

ValueError: shapes (1,49) and (8,3) not aligned: 49 (dim 1) != 8 (dim 0)